language: node_js

sudo: required

node_js:
  - "8.2.1"
services:
  - docker
install:
  - npm install
script:
  - npm run lint
  - npm run unit
  - npm run e2e
  - npm run build

  - docker build -t "$USER"/"$REPO" .
  - docker run -d -p 127.0.0.1:80:3008 "$USER"/"$REPO"
  - docker ps -a

  after_success:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "$USER"/"$REPO"