version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3005:3008"
  node2:
    environment:
      - P2P_PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3006:3008"
    links:
      - node1:node1
  node3:
    environment:
      - P2P_PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3007:3008"
    links:
      - node2:node2
